### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by ooow** [Guseyn/cutie-buffer#19]
Hello Guseyn, 

I'm interested in your library but I can't understand for what it should be used.

Please update the README file and provide more information about your library.

Thanks a lot.

#udate readme

**Comment by Guseyn** [comment]
Hello Goga,
Thank you for your interest. I'll fix typo in this readme(it's a cutie extension for buffer, not for fs) as soon as I reach my laptop.
In few words, all cutie libraries('cuties' as I call them) are based on cutie library (link in the readme), which is based on the Async Tree Pattern. 
So, before using 'cuties' you should read about cutie library and document about Async Tree Pattern(link is also available in the readme).
Hope, this comment will help you to get into the idea of this libraries.

**Comment by ooow** [comment]
Thanks for the answer, will wait for updates from you.

`Good luck! `
